[versions]
groovy3 = "3.0.23"
groovy3Versionrange = "[3,4)"
groovy4 = "4.0.24"
groovy4Versionrange = "[4,)"
junitJupiter = "5.13.4"
junitPlatform = "1.13.4"
kotlin = "2.2.20"
kotlinVersionrange = "[1.6,3)"
logback = "1.3.15"
logbackVersionrange = "[1.2,2)"
moshi = "1.15.2"
moshiVersionrange = "[1.12.0,2)"
okhttp = "5.2.1"
okhttpVersionrange = "[4,6)"
okio = "3.16.1"
okioVersionrange = "[3,4)"
slf4j = "2.0.17"
slf4jVersionrange = "[1.7,3)"

[libraries]
groovy3 = { module = "org.codehaus.groovy:groovy", version.ref = "groovy3" }
groovy3json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy3" }
groovy4 = { module = "org.apache.groovy:groovy", version.ref = "groovy4" }
groovy4json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy4" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junitPlatformCommons = { module = "org.junit.platform:junit-platform-commons", version.ref = "junitPlatform" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinCommon = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlinJdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinScriptingJvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm", version.ref = "kotlin" }
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiKotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpMockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okioJvm = { module = "com.squareup.okio:okio-jvm", version.ref = "okio" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[bundles]
groovy3 = ["groovy3", "groovy3json"]
groovy4 = ["groovy4", "groovy4json"]
kotlin = ["kotlin", "kotlinCommon", "kotlinJdk7", "kotlinJdk8", "kotlinReflect", "kotlinScriptingJvm", "kotlinStdlib", "kotlinTest"]
moshi = ["moshi", "moshiKotlin"]
okhttp = ["okhttp", "okhttpMockwebserver"]
okio = ["okio", "okioJvm"]

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
